aws_region="eu-central-1"
stack="devops-task"
fargate-task-service-role="devops-task-role"
aws_ecr="devops-task"
aws_profile="default"
source_repo_name="devops-task"
source_repo_branch="master"
image_repo_name="devops-task"
